// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxXncC6Ah-giwWSnvEtBG_S1X4etbjkJ4',
    appId: '1:353258999896:web:1e28f81f5700ebcf9bfa2d',
    messagingSenderId: '353258999896',
    projectId: 'slamm-app-496',
    authDomain: 'slamm-app-496.firebaseapp.com',
    storageBucket: 'slamm-app-496.firebasestorage.app',
    measurementId: 'G-J77L7RXZML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY-OGsPtaAFp1Siz6wHAd5RCOF-EMQKls',
    appId: '1:353258999896:android:e5251d09482ccb479bfa2d',
    messagingSenderId: '353258999896',
    projectId: 'slamm-app-496',
    storageBucket: 'slamm-app-496.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBho3w4VkOEfcohS2U2MLv49HsjYomREN8',
    appId: '1:353258999896:ios:e94f98c9b9ee714e9bfa2d',
    messagingSenderId: '353258999896',
    projectId: 'slamm-app-496',
    storageBucket: 'slamm-app-496.firebasestorage.app',
    iosBundleId: 'com.example.frontend.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBho3w4VkOEfcohS2U2MLv49HsjYomREN8',
    appId: '1:353258999896:ios:09e6bdc1c31adbe59bfa2d',
    messagingSenderId: '353258999896',
    projectId: 'slamm-app-496',
    storageBucket: 'slamm-app-496.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxXncC6Ah-giwWSnvEtBG_S1X4etbjkJ4',
    appId: '1:353258999896:web:ed603915151ca28e9bfa2d',
    messagingSenderId: '353258999896',
    projectId: 'slamm-app-496',
    authDomain: 'slamm-app-496.firebaseapp.com',
    storageBucket: 'slamm-app-496.firebasestorage.app',
    measurementId: 'G-38TMSRYRCW',
  );
}
